# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ad9bc2a1eac1701bb05d9cb4702e665f52078661f5df242feae663e0a6b1dc234f15202165be8a453f89de5153e561be99e678c13776a7ba8e5248f2383ee1a

test:
  secret_key_base: 4b79e4ad134c22bcaa0b548480a9e2696a35c752abcbed1a586ab2d9caa0c79da4fcb021bf68ff178685bf6c05e7d25ebdebffb63cafdb132995e9e038d214d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
